CREATE TABLE plantas(
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CATEGORIA_ID BIGINT(20) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  NOME2 VARCHAR(50),
  NOME3 VARCHAR(50),
  NOME4 VARCHAR(50),
  NOME5 VARCHAR(50),
  ESTRATO VARCHAR(15),
  ESPACOL VARCHAR(15),
  ESPACOH VARCHAR(15),
  TEMPO_COLHEITA VARCHAR(20),
  TEMPO_REBROTA VARCHAR(20),
  TEMPO_VIDA VARCHAR(20),
  VALOR_MUDA DECIMAL(10,2),
  VALOR_SEMENTE DECIMAL(10,2),
  VALOR_VENDA DECIMAL(10,2),
  INFORMACOES VARCHAR(500),
  IMAGEM LONGBLOB,
  IMAGEM2 LONGBLOB,
  SOMBREAMENTO SMALLINT(3),
  FOREIGN KEY (CATEGORIA_ID) REFERENCES categorias(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX plantas_categoria_id ON plantas(categoria_id);
CREATE INDEX plantas_nome ON plantas(NOME);

INSERT INTO plantas(CATEGORIA_ID, NOME, NOME2, NOME3, NOME4, NOME5, ESTRATO, ESPACOL, ESPACOH, TEMPO_COLHEITA, TEMPO_REBROTA, TEMPO_VIDA, VALOR_MUDA, VALOR_SEMENTE, VALOR_VENDA, INFORMACOES, IMAGEM, IMAGEM2, SOMBREAMENTO)
VALUES(2, 'Alface', 'Alface 2', 'Alface 3', 'Alface 4', 'Alface 5', 'Estrato', '10 cm', '12 cm', '5 meses', '2 dias', '1 ano', 1.12, 1.3, 0.23, 'Informações blas blas blas', null, null, 83);

INSERT INTO plantas(CATEGORIA_ID, NOME) VALUES(1, 'Brócolis');
INSERT INTO plantas(CATEGORIA_ID, NOME) VALUES(2, 'Batata');
INSERT INTO plantas(CATEGORIA_ID, NOME) VALUES(3, 'Mostarda');
INSERT INTO plantas(CATEGORIA_ID, NOME) VALUES(1, 'Couve');
INSERT INTO plantas(CATEGORIA_ID, NOME) VALUES(1, 'Hortelã');
INSERT INTO plantas(CATEGORIA_ID, NOME) VALUES(3, 'Manjericão');