CREATE TABLE usuarios (
  ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(50),
  EMAIL VARCHAR(50) NOT NULL,
  SENHA VARCHAR(59) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX usuarios_email ON usuarios(EMAIL);

CREATE TABLE roles (
  ID SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX roles_id ON roles(ID);

INSERT INTO roles(NOME) VALUES ('ADMIN');
INSERT INTO roles(NOME) VALUES ('DEFAULT_USER');
INSERT INTO roles(NOME) VALUES ('SPECIAL_USER');

CREATE TABLE permissoes (
  ID SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO permissoes(NOME) VALUES ('ADD_CATEGORIES');
INSERT INTO permissoes(NOME) VALUES ('REMOVE_CATEGORIES');
INSERT INTO permissoes(NOME) VALUES ('ALTER_CATEGORIES');
INSERT INTO permissoes(NOME) VALUES ('LIST_CATEGORIES');
INSERT INTO permissoes(NOME) VALUES ('ADD_PLANTS');
INSERT INTO permissoes(NOME) VALUES ('REMOVE_PLANTS');
INSERT INTO permissoes(NOME) VALUES ('ALTER_PLANTS');
INSERT INTO permissoes(NOME) VALUES ('LIST_PLANTS');
INSERT INTO permissoes(NOME) VALUES ('ADD_GARDENS');
INSERT INTO permissoes(NOME) VALUES ('REMOVE_GARDENS');
INSERT INTO permissoes(NOME) VALUES ('ALTER_GARDENS');
INSERT INTO permissoes(NOME) VALUES ('LIST_GARDENS');